config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # resources :prestations, only: :index
  resources :quotes, only: %i(new create)
  resources :contact_forms, only: %i(new create)

  get 'qui-sommes-nous', to: 'pages#about'
  get 'expertise', to: 'pages#expertise'
  get 'secteurs-dactivité', to: 'pages#secteurs', as: 'secteurs'
  get 'prestations', to: 'pages#prestations'
  get 'contact', to: 'pages#contact'
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format", to: "pages#robots"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  validates :rgpd, acceptance: true
  # validates :phone_number, format: { with: /A(0|\+33\s?|0033)[1-79](\d{8}|(\s\d{2}){4})\z/ }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :activity, dependent: :destroy
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  has_many :images
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :society_name, :email, :name, :prestation_type, :work_description, :rgpd, presence: true
  # validates :email, format: { with: /A[a-zA-Z0-9_-]+\.?[a-zA-Z0-9]+@{1}[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)?\.[a-z]{2,}\z/ }
  # validates :name, format: { with: /^[a-z]+\-?[a-z]+$/i }
  validates :rgpd, acceptance: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  def create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
        ContactFormMailer.with(contact_form: @contact_form).new_contact.deliver_now
        redirect_to root_path
        flash[:notice] = 'Votre message à bien été envoyé, merci !'
    elsif @contact_form.rgpd == false
      respond_to do |format|
        format.js
      end
    else
      raise
      redirect_to root_path
      flash[:alert] = 'Il y a eu un petit problème, appelez nous par téléphone le temps qu\'on règle ça !'
    end

    
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:first_name, :last_name, :email, :phone_number, :is_application, :message, :rgpd)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @header = "header-home.jpg"
    @activities = Activity.all
  end

  def about
    @header = "header-about.jpg"
  end

  def expertise
    @header = "header-expertise.jpg"
  end

  def secteurs
    @header = "header-activities.jpg"
    @activities = Activity.all
  end

  def prestations
    @header = "header-prestations.jpg"
  end

  def contact
    @header = "header-contact.jpg"

    @prestations = ["Accueil filtrage", "Surveillance statique", "Surveillance bailleurs sociaux", "Sécurité business", "Protection incendie et secours", "Intervention malveillante", "Sécurité évenementielle"]
    @quote = Quote.new
    @contact_form = ContactForm.new
  end

  def robots
    # Don't forget to delete /public/robots.txt
    respond_to :text
  end
end

app/controllers/prestations_controller.rb
class PrestationsController < ApplicationController
  def index
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      QuoteMailer.with(quote: @quote).new_quote.deliver_now
      redirect_to root_path
      flash[:notice] = 'Votre demande de devis à bien été envoyé, merci !'
    elsif @quote.rgpd == false
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path
      flash[:alert] = 'Il y a eu un petit problème, appelez nous par téléphone le temps qu\'on règle ça !'
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:society_name, :name, :prestation_type, :work_description, :email, :rgpd)
  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  layout :false
  before_action :init_sitemap

  def index
    
  end

  private

  def init_sitemap
    headers['Content-Type'] = 'application/xml'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contact_forms/create.js.erb
var submitProblemDiv = document.querySelector('#contact-submit-problem');
submitProblemDiv.innerHTML = '';
submitProblemDiv.innerHTML = '** Vous devez accepter les RGPD **'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about">
  <div id="about-text">
    <h2>La société <br> de sécurité</h2>
    <p>Quelque soit la nature de l’établissement concerné :</p>
    <ul>
      <li>- Bailleurs sociaux et copropriétés</li>
      <li>- Résidences et restauration rapide</li>
      <li>- Sites industriels</li>
      <li>- Sites en construction</li>
      <li>- Villa individuelle...</li>
      <li></li>
    </ul>
    <p>Les équipes de la société l'Azuréenne de protection jouent
      <span class="dif">un rôle primordial pour prévenir</span> tous risques de sinistres
      et de panique, dans un contexte accidentel et
      malveillant.
    </p>
    <p>
      Nous souscrivons à une véritable charte
      <span class="dif">garantissant le respect de la déontologie de la profession et une transparence</span> réelle
      quant au respect de la législation dans tous les domaines concernés. <br>
      <span class="dif">Cette loyauté envers nos clients</span> nous a forgé une autorité désormais reconnue.
    </p>
  </div>
  <div class="stick-to">
    <%= image_tag('about-police.png') %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="pink">
  <div id="contact">
    <div id="contactez-nous">
      <div id="contact-elements">
        <div id="contact-form">
        <h2 class="white top scale-up-phone">Contactez-nous sans engagement</h2>
         <p class="red"> Les champs marqués d’un * sont obligatoires </p>
          <%= simple_form_for @contact_form, remote: true do |f| %>
          <label for="contact_form_first_name", class="input"> Prenom:<span class="stars">*</span> </label>
            <%= f.input :first_name, required: true, label: false %>
            <label for="contact_for_last_name", class="input"> Nom:<span class="stars">*</span> </label>
            <%= f.input :last_name, required: true, label: false %>
            <label for="contact_form_email", class="input"> Email:<span class="stars">*</span> </label>
            <%= f.input :email, required: true,  label: false %>
            <label for="contact_form_phone_number", class="input"> Telephone:<span class="stars">*</span> </label>
            <%= f.input :phone_number,  label: false %>
            <p class="white ital"><%= "Souhaitez-vous déposer une candidature spontanée ?" %></p>
            <div class="oui">
              <%= f.input :is_application, as: :boolean, required: true, label: false %>
              <label for="contact_form_is_application">
              <p class="white ital"> Oui <span class="stars">*</span></p>
            </div>
            <label for="contact_form_message", class="input"> Message<span class="stars">*</span> </label>
            <%= f.input :message, type: :text, label: false %>
            <div id="rgpd-checkbox">
              <p class="white">
                En soumettant ce formulaire, j’accepte que les informations saisies dans ce formulaire soient traitées pour permettre d'être
                contacté dans le cadre des services et activités de la société de sécurité l'Azuréenne de protection.
              </p>
              <div class="oui">
                <%= f.input :rgpd, as: :boolean, required: true, label: false %>
                 <label for="contact_form_rgpd">
                <p class="white pad"> RGPD<span class="stars">*</span> </p>
              </div>
            </div>
            <%= f.submit value="Envoyer", :class => "button" %>
            <div id="contact-submit-problem"></div>
          <% end %>
        </div>
        <div id="contact-text">
          <h3 class="red style add">Adresse</h3>
          <p class="white">
            Parc de la Roseraie Bat<br>
            A1 20 Traverse de<br>
            la Buzine13011 Marseille<br>
          </p>
          <h3 class="red style num">Numéros</h3>
          <div class="phones">
            <i class="fa fa-phone" aria-hidden="true"></i>
            <p class="white">04.91.44.90.11</p>
          </div>
          <div class="phones">
            <i class="fa fa-mobile" aria-hidden="true"></i>
            <p class="white">04.91.44.89.58</p>
          </div>
          <h3 class="red style inf">Infos légales</h3>
          <p class="white narrow">
            L'Azuréenne de protection<br>
          <span class="weight"> SIRET </span> : 497 578 898 00049<br>
           <span class="weight"> Président de la SAS </span> : Attila SIMKO<br>
            Sité Hébergé chez Ionos<br>
            Tout droit de reproduction soumis à autorisation expresse.<br>
          </p>
          <p class="white narrow">
            Les données communiquées via ce formulaire ne seront pas transmises à des tiers. Elles sont collectées à des fins de gestion des services
            et activités de la société de sécurité l'Azuréenne de protection.
          </p>
          <p class="white narrow">
            Les données fournies seront conservées pour une durée maximale de 3 ans. Vous disposez d’un droit d’accès, de rectification, d’effacement,
            de limitation, de portabilité et d’opposition aux données personnelles vous concernant. Pour exercer ce droit, merci d’effectuer votre demande
            auprès de la société de sécurité l'Azuréenne de protection (par mail ou par courrier).
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
  <div id="quote">
    <div id="quote-elements">
      <div id="quote-text">
        <h3 class="red type">
          l'Azuréenne de protection, la sécurité par excellence pour les prestations de sécurité et gardiennage, notamment:
        </h3>
        <p>
          Contrôles de sécurité<br>
          Surveillance statique<br>
          Surveillance mobile notamment pour
          bailleurs sociaux<br>
          Protection incendie et secours<br>
          Protection contre les actions de
          malveillance<br>
          Sécurité de vos évènements<br>
          Security Business<br>
        </p>
        <p>
          Les données communiquées via ce formulaire ne seront pas transmises à des tiers. Elles sont collectées à des fins de gestion des
          services et activités de la société de sécurité l'Azuréenne de protection.
        </p>
        <p>
          Les données fournies seront conservées pour une durée maximale de 3 ans. Vous disposez d’un droit d’accès,
          de rectification, d’effacement, de limitation, de portabilité et d’opposition aux données personnelles vous concernant. Pour exercer ce droit,
          merci d’effectuer votre demande auprès de la société de sécurité l'Azuréenne de protection (par mail ou par courrier).
        </p>
      </div>
      <div id="quote-form">
        <h2 class="title-two">Demandez un devis gratuit sans engagement</h2>
        <p class="red"> Les champs marqués d’un * sont obligatoires </p>
        <%= simple_form_for @quote, remote:true do |f| %>
          <%= f.input :society_name, required: true, label: "Nom de la société" %>
          <%= f.input :name, required: true, label: 'Nom et prénom' %>
          <%= f.input :email, required: true, label: "Email"%>
          <label for="quote_prestation_type"> Votre prestation est </label>
          <%= f.input :prestation_type, collection: @prestations, prompt: "Merci de sélectionner ici…", label: false %>
          <label for="quote_prestation_type"> Décrivez ici votre besoin </label>
          <%= f.input :work_description, type: :text, label: false %>
          <div id="rgpd-checkbox">
            <p>
                En soumettant ce formulaire, j’accepte que les informations saisies dans ce formulaire soient traitées pour permettre d'être
                contacté dans le cadre des services et activités de la société de sécurité l'Azuréenne de protection.
              </p>
              <div class="oui">
                <%= f.input :rgpd, as: :boolean, required: true, label: false %>
                 <label for="contact_form_rgpd">
                <p class="pad"> RGPD<span class="stars">*</span> </p>
              </div>
          </div>
          <%= f.submit value="Envoyer", :class => "button"  %>
          <div id="quote-submit-problem"></div>
        <% end %>
      </div>
    </div>
  </div>

app/views/pages/expertise.html.erb
<div id="expertise">
  <div class="expertise-line">
    <%= image_tag('diagnostic.png', id: 'diagnostic') %>
    <div class="expertise-line-text">
      <p>Avant chaque intervention, l’Azuréenne réalise un diagnostic.</p>
      <ul class="list">
        <li> <span class="col-li"> - </span> En identifiant les risques et en les hiérarchisant.</li>
        <li><span class="col-li"> - </span> En repérant les failles d’insécurité.</li>
        <li><span class="col-li"> - </span> En élaborant un plan d’action en accord aux législations et procédures du site ou de l’entreprise.</li>
        <li><span class="col-li"> - </span> En consolidant les facteurs qui contribuent à une meilleure prévention.</li>
      </ul>
    </div>
    <%= image_tag('expertise2.jpg', class: "pic-diagnostic") %>
  </div>

  <div class="expertise-line">
    <div class="expertise-line-text text-habilete">
      <p>
        Vous rencontrerez au sein de notre entreprise, des hommes dynamiques en excellente condition physique,
        ayant une grande capacité d’adaptation et une véritable vocation de la protection des biens et des personnes.
        Notre expérience due à de nombreuses interventions et opérations fait de l'Azuréenne de protection une société différente où
        notre professionnalisme et notre vécu nous distinguent par la qualité de nos prestations quelque soit la zone géographique.
      </p>
    </div>
    <%= image_tag('expertise3.jpg', class: "pic-habilete") %>
    <%= image_tag('habilete.png', id: 'habilete') %>
  </div>

  <div class="expertise-line tab">
    <%= image_tag('suivi-terrain.png', id: 'suivi-terrain') %>
    <div class="expertise-line-text text-suivi-terrain">
      <p>
        La souplesse et l’adaptabilité de la société l'Azuréenne de protection ainsi que notre capacité de réaction,
        permettent de coller en permanence aux attentes de nos clients.
      </p>
      <p>
        Le suivi des actions mises en place est assuré par nos équipes. Cet encadrement est réalisé par de véritables
        professionnels de la Sécurité. Chaque chef de secteur dispose d’une solide expérience dans le domaine dont il a la responsabilité.
      </p>
      <p>
        Sérieux de notre engagement sur la plan de l’assurance qualité, tous nos agents possèdent l’agrément
        préfectoral ASP, SST, EPI, et certains SSIAP1, SSIAP2, SSIAP3 et HOBO (services relatifs aux normes et aux procédures).
      </p>
    </div>
    <%= image_tag('expertise6.jpg', class: "pic-suivi-terrain") %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-contain">
  <div id="frame-one">
    <h2 class="tel-home">Notre savoir faire</h2>

    <div class="cards">
      <div class="savoir-faire-card">
        <div class="hover-one">
          <div class="hover-lay"></div>
          <%= image_tag('stormtrooper.jpg', alt: 'Azureenne securité - le rempart', class: 'savoir-faire-card-img') %>
          <div class="content-details">
            <p class="sfc"> l'Azuréenne de protection<p>
          </div>
        </div>
        <p class="savoir-faire-card-title">La société de sécurité l'Azuréenne de protection est le rempart actif de votre sécurité</p>
        <p class="savoir-faire-card-description">
          La compétence de nos agents, augmentée de la maîtrise de nos techniques font de la société de sécurité l'Azuréenne de protection
          votre partenaire indispensable et incontournable.
        </p>
      </div>
      <div class="savoir-faire-card">
        <div class="hover-one">
          <div class="hover-lay"></div>
          <%= image_tag('jumelles.jpg', alt: 'azureenne securité - les agents', class: 'savoir-faire-card-img') %>
          <div class="content-details">
            <p class="sfc"> Nos agents<p>
            <p class="sfc">de sécurité<p>
          </div>
        </div>
        <p class="savoir-faire-card-title">Des agents de sécurité dynamiques au service de la protection des biens et des personnes</p>
        <p class="savoir-faire-card-description new">
          Des agents de sécurité en excellente condition physique, ayant une grande capacité d’adaptation et une véritable
          vocation de la protection des biens et des personnes.
        </p>
      </div>
      <div class="savoir-faire-card">
        <div class="hover-one">
          <div class="hover-lay"></div>
          <%= image_tag('application.jpg', alt: "azureenne securité - l'application", class: 'savoir-faire-card-img') %>
          <div class="content-details">
            <p class="sfc"> Notre application <p>
          </div>
        </div>
        <p class="savoir-faire-card-title">Une application simple et performante</p>
        <p class="savoir-faire-card-description marg-tel plus">
          Enregistrer la prise de service de l’agent, sa géolocalisation jusqu’à l’enregistrement d’une main courante électronique :
          notre application sur-mesure simplifie notre service de sécurité.
        </p>
      </div>
    </div>
  </div>

  <div id="frame-two">
    <h2 class="tel-home">Une triple stratégie</h2>

    <div class="strategie">
      <div class="strategie-card">
        <div class="number">
          <p class="opacity"> 1</p>
          <span class="strat">diagnostic</span>
        </div>
      </div>
      <div class="strategie-card">
        <div class="number">
          <p class="opacity"> 2</p>
          <span class="strat">Professionalisme</span>
        </div>
      </div>
      <div class="strategie-card">
        <div class="number">
          <p class="opacity"> 3</p>
          <span class="strat">Suivi de terrain</span>
        </div>
      </div>
    </div>
  </div>
  <h2 class="tel-home start">Nos secteurs d'activités</h2>
  <div id="frame-three">
    <div class="secteurs flip-card">
      <% @activities.each_with_index do |activity, index| %>
        <div class="grid-<%= index %>   grid">
          <h3 class="vertical">
            <%= activity.title == "Bâtiment" ? activity.subtitle : activity.title %>
          </h3>
          <div class="flip-card-inner">
            <div class="flip-card-front">
              <% if !activity.images.find_by(page: "home").nil? %>
                <%= image_tag(activity.title.gsub(/\s+/, "").downcase + "1.jpg") %>
              <% else %>
                <%= image_tag('https://via.placeholder.com/325x688') %>
              <% end %>
            </div>
            <div class="flip-card-back">
              <div class="flip-text">
              <h3 class="card-tit"><%= activity.title == "Bâtiment" ? simple_format(activity.subtitle) : simple_format(activity.title) %></h3>
              <p><%= simple_format(activity.description) %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div id="frame-four" class="for-computer">
    <h2 class="parts phon">Nos partenaires</h2>
    <div>
      <ul class="partners-logos">
        <li><%= image_tag('partenaires/gtm.png', width:"85", height: "83") %></li>
        <li><%= image_tag('partenaires/mcdonalds.png', width:"80", height: "80") %></li>
        <li class="moove"><%= image_tag('partenaires/veolia.png', width:"168", height: "168") %></li>
        <li class="moove"><%= image_tag('partenaires/eurovia.png', width:"144.44", height: "81.25") %></li>
        <li class="moove"><%= image_tag('partenaires/eiffage.png', width:"193", height: "56") %></li>
        <li class="moove"><%= image_tag('partenaires/citya.png', width:"85", height: "85") %></li>
        <li class="moove"><%= image_tag('partenaires/foncia.png', width:"85", height: "85") %></li>
        <li class="moove"><%= image_tag('partenaires/radisson.png', width:"193", height: "56") %></li>
        <li class="moove"><%= image_tag('partenaires/villogia.png', width:"85", height: "85") %></li>
        <li class="moove"><%= image_tag('partenaires/aldi.png', width:"85", height: "85") %></li>
        <li class="moove"><%= image_tag('partenaires/burger-king.png', width:"85", height: "85") %></li>
      </ul>
    </div>
  </div>
  <div id="frame-four" class="for-tel">
    <h2 class="parts tel-home">Nos partenaires</h2>
    <div>
      <ul class="partners-logos">
        <li><%= image_tag('partenaires/gtm.png', width:"42.5", height: "41.5") %></li>
        <li><%= image_tag('partenaires/mcdonalds.png', width:"40", height: "40") %></li>
        <li><%= image_tag('partenaires/veolia.png', width:"84", height: "84") %></li>
        <li><%= image_tag('partenaires/eurovia.png', width:"72.22", height: "40.37") %></li>
        <li><%= image_tag('partenaires/eiffage.png', width:"65", height: "20") %></li>
        <li><%= image_tag('partenaires/citya.png', width:"40", height: "40") %></li>
        <li><%= image_tag('partenaires/foncia.png', width:"45", height: "45") %></li>
        <li><%= image_tag('partenaires/radisson.png', width:"85", height: "25") %></li>
        <li><%= image_tag('partenaires/villogia.png', width:"55", height: "55") %></li>
        <li><%= image_tag('partenaires/aldi.png', width:"40", height: "40") %></li>
        <li><%= image_tag('partenaires/burger-king.png', width:"45", height: "45") %></li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/robots.txt.erb
<% if Rails.env == "production" %>
  "User-Agent: *\n"
  "Disallow: \n"
<% else %>
  "User-Agent: *\n"
  "Noindex: /\n"
<% end %>

<%= "\nSitemap: #{root_url}sitemap.xml" %>

app/views/pages/secteurs.html.erb
<div id="secteurs">
  <% img_nb = 1 %>
  <% @activities.each do |activity| %>
    <% if !activity.images.find_by(page: "expertise").nil? %>
        <div class="activity">
          <div class="activity-images">
            <%= image_tag(activity.images[1].file_name, class:"image-#{img_nb}")  %>
            <div class= "line line-<%= img_nb %>">
            
            </div>
            <% img_nb += 1 %>   
            <%= image_tag(activity.images[2].file_name, class:"image-two")  %>
          </div>
          <div class="activities-texts">
            <h2><%= activity.title == "Bâtiment" ? activity.subtitle : activity.title %></h2>
            <h3><%= activity.subtitle if activity.title != "Bâtiment" %></h3>
            <p><%= activity.description %></p>
          </div>
        </div>
      <% end %> 
  <% end %>
</div>

app/views/quotes/create.js.erb
var submitProblemDiv = document.querySelector('#quote-submit-problem');
submitProblemDiv.innerHTML = '';
submitProblemDiv.innerHTML = '** Vous devez accepter les RGPD **'

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class=tel-format>
    <%= image_tag('logo.png') %>
  </div>
  <div>
    <h3 class="tit">Informations</h3>
    <p class="sub">
      Parc de la Roseraie Bat. A1<br>
      20 Traverse de la Buzine<br>
      13011 Marseille
    </p>
    <p class="sub">04 91 44 90 11</p>
    <p class="sub">04 91 44 89 58</p>
  </div>
  <div>
    <h3 class="tit">A propos</h3>
    <p class="sub">Du lundi au vendredi <br> De 9h00 à 18h00</p>
  </div>
  <div>
    <h3 class="tit">Mentions légales</h3>
    <p class="sub">
      AUT 013-2113-07-14-20140385158 Article L612-14 – Modifié par LOI<br>
      n°2014-742 du 1er juillet 2014 – art. 7 :<br>
      L’autorisation d’exercice ne confère aucune<br>
      prérogative de puissance publique à l’entreprise<br>
      ou aux personnes qui en bénéficient.
    </p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="<%= @header == "header-home.jpg" ? 'home-header-height' : 'banner' %>" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path(@header.nil? ? "header-contact.jpg" : @header) %>);">
  <div class="contain">
    <p>L'AZUREENNE DE PROTECTION</p>
    <h1>
      <% if @header == "header-home.jpg" %>
        Mieux vaut prévenir<br>
        que guérir...
      <% elsif @header == "header-about.jpg" %>
        Qui sommes-nous ?
      <% elsif @header == "header-activities.jpg" %>
        Nos secteurs d'activités
      <% elsif @header == "header-prestations.jpg" %>
        Nos prestations
      <% elsif @header == "header-contact.jpg" %>
        Nous contacter / Devis
      <% elsif @header == "header-expertise.jpg" %>
        Nos expertises
      <% end %>
    </h1>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <%= link_to image_tag('logo.png', alt: "L'azuréenne de protection", id: 'logo'), root_path %>
  </div>
  <ul class="menus" id="nav-computer">
      <li><%= link_to 'QUI SOMMES-NOUS ?', qui_sommes_nous_path %></li>
      <li class="bar">|</li>
      <li><%= link_to 'EXPERTISE', expertise_path %></li>
      <li class="bar">|</li>
      <li><%= link_to 'SECTEURS D\'ACTIVITÉ', secteurs_path %></li>
      <li class="bar">|</li>
      <li><%= link_to 'PRESTATIONS', prestations_path %></li>
      <li class="bar">|</li>
      <li><%= link_to 'CONTACT', contact_path %></li>
  </ul>

  <div class="collapse navbar-collapse" id="navbarSupportedContent nav-tel">
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
            <%= image_tag "menu.png", class: "dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to 'QUI SOMMES-NOUS ?', qui_sommes_nous_path, class: "dropdown-item" %>
              <%= link_to 'EXPERTISE', expertise_path, class: "dropdown-item" %>
              <%= link_to 'SECTEURS D\'ACTIVITÉ', secteurs_path, class: "dropdown-item" %>
              <%= link_to 'PRESTATIONS', prestations_path, class: "dropdown-item" %>
              <%= link_to 'CONTACT', contact_path, class: "dropdown-item" %>
            </div>
        </li>
      </ul>
  </div>
</div>